import type { Metadata } from "next";


import {  Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import AppSidebar from "./(routes)/(root)/components/AppSidebar/AppSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Navbar } from "@/components/shared";
import Footer from "@/components/shared/Footer/Footer";
import { Toaster } from "@/components/ui/sonner";


const spaceGrotesk = Space_Grotesk({

  variable:"--font-space-grotesk",
  subsets: ["latin"],

}

)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <ClerkProvider>
    <html lang="en">
      <body
        className={`${spaceGrotesk.className}  antialiased`}
      > 
       <SidebarProvider>
      <AppSidebar />
      <div className="w-full bg-stone-100 flex flex-col min-h-screen">
        <Navbar/>

      
        <main className="flex-1/2"> {children}</main>
        <Toaster/>
        <Footer/>

        </div>

        </SidebarProvider>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
